language: csharp
solution: ConsoleCalculator.sln
mono: none
dotnet: 2.1.502
install:
    - dotnet restore
script:
    - dotnet build
    - dotnet test ConsoleCalculator.Tests/ConsoleCalculator.Tests.csproj 

